version: 2.0

defaults: &defaults
  working_directory: ~/node-circle
  docker:
    - image: kkarczmarczyk/node-yarn:8.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: run-yarn
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: test
          command: npm test
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: lint
          command: npm run lint

workflows:
  version: 2
  build-lint-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
