version: 2.0

defaults: &defaults
  working_directory: ~/node-circle
  docker:
    - image: circleci/node:8.1.4

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: install-yarn-jest
          command: 'sudo npm i -g yarn jest eslint'
      - run:
          name: run-yarn
          command: yarn install
  test:
    <<: *defaults
    steps:
      - run:
          name: test
          command: npm test
  eslint:
    <<: *defaults
    steps:
      - run:
          name: lint
          command: npm run lint

workflows:
  version: 2
  build-eslint-and-test:
    jobs:
      - build
      - test:
          - requires:
              - build
      - eslint:
          - requires:
              - build
