version: 2.0

defaults: &defaults
  working_directory: ~/node-circle
  docker:
    - image: circleci/node:8.1.4

jobs:
  build:
    <<: *defaults
    steps:
      - run: echo 'Build!'
  test:
    <<: *defaults
    steps:
      - run: echo 'Test!'
  lint:
    <<: *defaults
    steps:
      - run: echo 'Lint!'

workflows:
  version: 2
  build:
    jobs:
      - build
      - test
      - lint
