version: 2

defaults: &defaults
  working_directory: ~/node-circle-elastic-beanstalk
  docker:
    - image: node:8.4.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: install dependencies
          command: yarn install --freeze-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: test
          command: npm test
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: lint
          command: npm run lint
  deploy:
    working_directory: ~/node-circle-elastic-beanstalk
    docker:
      - image: coxauto/aws-ebcli
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: ./.circleci/generate_configuration.sh
      - run: eb use $APPLICATION_ENVIRONMENT
      - run: eb deploy --timeout 45

workflows:
  version: 2
  build-lint-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
            - lint
      - deploy:
          requires:
            - hold
